/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Get a single process by PID */
export declare function getProcess(pid: number, options?: GetProcessesOptions | undefined | null): ProcessInfo | null

/** Get all running processes */
export declare function getProcesses(options?: GetProcessesOptions | undefined | null): Array<ProcessInfo>

/** Options for controlling which optional fields to include */
export interface GetProcessesOptions {
  /** Optional fields to include: "ppid", "memory", "startTime" */
  include?: Array<string>
}

/** Information about a running process */
export interface ProcessInfo {
  /** Process ID */
  pid: number
  /** Process name */
  name: string
  /** Full path to the executable (may be null if not accessible) */
  path?: string
  /** Whether this process owns the foreground window */
  isForeground: boolean
  /** Parent process ID (optional, requires include: ["ppid"]) */
  ppid?: number
  /** Memory usage in bytes (optional, requires include: ["memory"]) */
  memory?: number
  /** Process start time as Unix timestamp in milliseconds (optional, requires include: ["startTime"]) */
  startTime?: number
}
