/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getForeground(): Promise<NativeForeground>

export declare function getForegroundSync(): NativeForeground

export declare function getProcess(pid: number): Promise<NativeProcess | null>

export declare function getProcessSync(pid: number): NativeProcess | null

export declare function listProcesses(pids?: Array<number> | undefined | null): Promise<Array<NativeProcess>>

export declare function listProcessesSync(pids?: Array<number> | undefined | null): Array<NativeProcess>

export interface NativeForeground {
  status: string
  pid?: number
  source?: string
  reason?: string
}

export interface NativeProcess {
  pid: number
  name?: string
  parentPid?: number
  executablePath?: string
  memoryBytes?: number
  startedAt?: number
}
